---
- name: galaxy-user-settings
  src: https://github.com/EvgeniyBlinov/ansible-role-user-settings.git
  #version: v0.0.0-patch3
- name: galaxy-openvpn
  src: https://github.com/EvgeniyBlinov/ansible-role-server-openvpn.git
