#!/bin/bash

WEBHOOK_URL="{{ monitoring__ssh__login__webhook_url }}"
MESSAGE_ATTR={{ 'text' if monitoring__ssh__login__webhook_url is search('slack') else 'content' }}

HOST_INFO=$(curl -s https://ipinfo.io/${PAM_RHOST} | tr '"' "'")

# Let's capture only open_session and close_session events (login and logout).
case "$PAM_TYPE" in
    open_session)
        PAYLOAD=" { \"${MESSAGE_ATTR}\": \"$PAM_USER logged in (remote host: $PAM_RHOST, host info: ${HOST_INFO}).\" }"
        ;;
    close_session)
        PAYLOAD=" { \"${MESSAGE_ATTR}\": \"$PAM_USER logged out (remote host: $PAM_RHOST, host info: ${HOST_INFO}).\" }"
        ;;
esac

# Let's only perform a request if there is an actual payload to send.
if [ -n "$PAYLOAD" ] ; then
    curl -X POST -H 'Content-Type: application/json' -d "$PAYLOAD" "$WEBHOOK_URL"
fi
