---
- hosts: all
  roles:
    - role: galaxy-user-settings
      tags: galaxy-user-settings
    - role: firewall
      tags: firewall
    #- role: ingress
      #tags: ingress
    - role: monitoring
      tags: monitoring
